version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "998072949015"
    AWS_DEFAULT_REGION: "us-east-2"
    IMAGE_REPO_NAME: "wine-quality-container"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      # you must keep the whole pipe in one line, unquoted
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - cd part2b-sagemaker-container
      - docker build --platform linux/amd64 -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

artifacts:
  files: []
