version: 0.2

env:
  variables:
    IMAGE_NAME: wine-quality-container

phases:
  pre_build:
    commands:
      - echo "==> Logging in to Amazon ECR..."
      # Grab your AWS account ID dynamically
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Account: $ACCOUNT_ID | Region: $AWS_DEFAULT_REGION"
      # Log in to ECR (no interactive TTY)
      - aws ecr get-login-password \
          --region $AWS_DEFAULT_REGION \
        | docker login \
          --username AWS \
          --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # Define the full repository URI
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME

  build:
    commands:
      - echo "==> Building Docker image..."
      - docker build \
          --platform linux/amd64 \
          -t $IMAGE_NAME .
      - echo "==> Tagging image for ECR…"
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "==> Pushing to ECR…"
      - docker push $REPOSITORY_URI:latest
      - echo "==> Build completed on $(date)"
